runtime: nodejs14
service: inventory
env: standard

handlers:
  - url: /(.*\.(gif|png|jpeg|jpg|css|js|ico|svg))$
    static_files: dist/\1
    upload: dist/(.*)

instance_class: F1
automatic_scaling:
  max_instances: 1
  min_instances: 0
  min_idle_instances: 0
  max_idle_instances: 1
